# .github/workflows/deploy-to-aws.yml

name: Deploy to AWS

# This workflow runs on every push to the 'main' branch
on:
  push:
    branches:
      - main
      - master

# These permissions are required for the OIDC token exchange and code checkout.
permissions:
  id-token: write # This is required to get the OIDC JWT token
  contents: read  # This is required to checkout the repository's code

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # --- SETUP UV ---
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # The ARN of the role you created in the AWS IAM console
          role-to-assume: arn:aws:iam::230150030147:role/aws-to-github
          # The AWS region to deploy to
          aws-region: us-east-1 # Change this to your desired region

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install CDK CLI
        run: npm install -g aws-cdk@latest

      # --- THE UV WAY ---
      - name: Install Dependencies
        run: uv sync --frozen # this installs dependencies based on your lockfile (uv.lock)

      - name: Deploy with AWS CDK
        # 'uv run' ensures the deploy uses the exact libraries in your lockfile
        run: uv run cdk deploy --all --require-approval never